[package]
name = "token-escrow"
version = "0.9.0"
description = "Solana escrow implementation using account compression"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "token_escrow"

[features]
no-entrypoint = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
custom-heap = []
default = ["custom-heap", "idl-build"]
test-sbf = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { workspace = true, features = ["init-if-needed"] }
light-compressed-token = { workspace = true }
light-system-program = { workspace = true }
account-compression = { workspace = true }
light-hasher = { path = "https://github.com/Lightprotocol/light-protocol/merkle-tree/hasher", version = "1.1.0" }
light-verifier = { path = "https://github.com/Lightprotocol/light-protocol/circuit-lib/verifier", version = "1.1.0" }
light-sdk = { features = ["legacy"] }

[target.'cfg(not(target_os = "solana"))'.dependencies]
solana-sdk = { workspace = true }

[dev-dependencies]
solana-program-test = { workspace = true }
light-test-utils = { version = "1.2.0", path = "https://github.com/Lightprotocol/light-protocol/test-utils", features = ["devenv"] }
reqwest = "0.12"
tokio = { workspace = true }
light-prover-client = { path = "https://github.com/Lightprotocol/light-protocol/circuit-lib/light-prover-client", version = "1.2.0" }
num-bigint = "0.4.6"
num-traits = "0.2.19"
spl-token = { workspace = true }
anchor-spl = { workspace = true }
