[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
protocol = "269WdsAWfRPf1qB4LVM5Zs11CtwfnvcCF91v8NKd4rck"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
